{{- if .Values.placement.enabled }}
kind: Ingress
apiVersion: networking.k8s.io/v1beta1

metadata:
  name: nova-placement-api
  labels:
    system: openstack
    type: api
    component: nova
  annotations:
    ingress.kubernetes.io/configuration-snippet: |
      {{- include "utils.snippets.set_openstack_request_id" . | indent 6 }}
  {{- if .Values.use_tls_acme }}
    kubernetes.io/tls-acme: "true"
  {{- end }}
spec:
  tls:
     - secretName: tls-{{include "placement_api_endpoint_host_public" . | replace "." "-" }}
       hosts: [{{include "placement_api_endpoint_host_public" .}}]
  rules:
    - host: {{include "placement_api_endpoint_host_public" .}}
      http:
        paths:
        - path: /
          backend:
            serviceName: nova-placement-api
            servicePort: {{.Values.global.placementApiPortInternal}}
{{- end }}
