dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.3.40
  - name: memcached
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.0.7
  - name: utils
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.3.4
  - name: region_check
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.2
